dos2unix ./database.cpp                                      ./database.cpp
dos2unix ./general.cpp                                       ./general.cpp
dos2unix ./main.cpp                                          ./main.cpp
dos2unix ./operations.cpp                                    ./operations.cpp
dos2unix ./random.cpp                                        ./random.cpp
dos2unix ./database.hpp                                      ./database.hpp
dos2unix ./general.hpp                                       ./general.hpp
dos2unix ./operations.hpp                                    ./operations.hpp
dos2unix ./random.hpp                                        ./random.hpp
dos2unix ./tokenizer.hpp                                     ./tokenizer.hpp
dos2unix ./boost/config.hpp                                  ./boost/config.hpp
dos2unix ./boost/cstdint.hpp                                 ./boost/cstdint.hpp
dos2unix ./boost/integer_traits.hpp                          ./boost/integer_traits.hpp
dos2unix ./boost/iterator.hpp                                ./boost/iterator.hpp
dos2unix ./boost/limits.hpp                                  ./boost/limits.hpp
dos2unix ./boost/operators.hpp                               ./boost/operators.hpp
dos2unix ./boost/random.hpp                                  ./boost/random.hpp
dos2unix ./boost/static_assert.hpp                           ./boost/static_assert.hpp
dos2unix ./boost/config/posix_features.hpp                   ./boost/config/posix_features.hpp
dos2unix ./boost/config/select_compiler_config.hpp           ./boost/config/select_compiler_config.hpp
dos2unix ./boost/config/select_platform_config.hpp           ./boost/config/select_platform_config.hpp
dos2unix ./boost/config/select_stdlib_config.hpp             ./boost/config/select_stdlib_config.hpp
dos2unix ./boost/config/suffix.hpp                           ./boost/config/suffix.hpp
dos2unix ./boost/config/user.hpp                             ./boost/config/user.hpp
dos2unix ./boost/config/compiler/borland.hpp                 ./boost/config/compiler/borland.hpp
dos2unix ./boost/config/compiler/comeau.hpp                  ./boost/config/compiler/comeau.hpp
dos2unix ./boost/config/compiler/common_edg.hpp              ./boost/config/compiler/common_edg.hpp
dos2unix ./boost/config/compiler/compaq_cxx.hpp              ./boost/config/compiler/compaq_cxx.hpp
dos2unix ./boost/config/compiler/gcc.hpp                     ./boost/config/compiler/gcc.hpp
dos2unix ./boost/config/compiler/greenhills.hpp              ./boost/config/compiler/greenhills.hpp
dos2unix ./boost/config/compiler/hp_acc.hpp                  ./boost/config/compiler/hp_acc.hpp
dos2unix ./boost/config/compiler/intel.hpp                   ./boost/config/compiler/intel.hpp
dos2unix ./boost/config/compiler/kai.hpp                     ./boost/config/compiler/kai.hpp
dos2unix ./boost/config/compiler/metrowerks.hpp              ./boost/config/compiler/metrowerks.hpp
dos2unix ./boost/config/compiler/mpw.hpp                     ./boost/config/compiler/mpw.hpp
dos2unix ./boost/config/compiler/sgi_mipspro.hpp             ./boost/config/compiler/sgi_mipspro.hpp
dos2unix ./boost/config/compiler/sunpro_cc.hpp               ./boost/config/compiler/sunpro_cc.hpp
dos2unix ./boost/config/compiler/vacpp.hpp                   ./boost/config/compiler/vacpp.hpp
dos2unix ./boost/config/compiler/visualc.hpp                 ./boost/config/compiler/visualc.hpp
dos2unix ./boost/config/platform/aix.hpp                     ./boost/config/platform/aix.hpp
dos2unix ./boost/config/platform/beos.hpp                    ./boost/config/platform/beos.hpp
dos2unix ./boost/config/platform/bsd.hpp                     ./boost/config/platform/bsd.hpp
dos2unix ./boost/config/platform/cygwin.hpp                  ./boost/config/platform/cygwin.hpp
dos2unix ./boost/config/platform/hpux.hpp                    ./boost/config/platform/hpux.hpp
dos2unix ./boost/config/platform/irix.hpp                    ./boost/config/platform/irix.hpp
dos2unix ./boost/config/platform/linux.hpp                   ./boost/config/platform/linux.hpp
dos2unix ./boost/config/platform/macos.hpp                   ./boost/config/platform/macos.hpp
dos2unix ./boost/config/platform/solaris.hpp                 ./boost/config/platform/solaris.hpp
dos2unix ./boost/config/platform/win32.hpp                   ./boost/config/platform/win32.hpp
dos2unix ./boost/config/stdlib/dinkumware.hpp                ./boost/config/stdlib/dinkumware.hpp
dos2unix ./boost/config/stdlib/libstdcpp3.hpp                ./boost/config/stdlib/libstdcpp3.hpp
dos2unix ./boost/config/stdlib/modena.hpp                    ./boost/config/stdlib/modena.hpp
dos2unix ./boost/config/stdlib/msl.hpp                       ./boost/config/stdlib/msl.hpp
dos2unix ./boost/config/stdlib/roguewave.hpp                 ./boost/config/stdlib/roguewave.hpp
dos2unix ./boost/config/stdlib/sgi.hpp                       ./boost/config/stdlib/sgi.hpp
dos2unix ./boost/config/stdlib/stlport.hpp                   ./boost/config/stdlib/stlport.hpp
dos2unix ./boost/config/stdlib/vacpp.hpp                     ./boost/config/stdlib/vacpp.hpp
dos2unix ./boost/detail/limits.hpp                           ./boost/detail/limits.hpp
dos2unix ./boost/random/additive_combine.hpp                 ./boost/random/additive_combine.hpp
dos2unix ./boost/random/bernoulli_distribution.hpp           ./boost/random/bernoulli_distribution.hpp
dos2unix ./boost/random/cauchy_distribution.hpp              ./boost/random/cauchy_distribution.hpp
dos2unix ./boost/random/exponential_distribution.hpp         ./boost/random/exponential_distribution.hpp
dos2unix ./boost/random/geometric_distribution.hpp           ./boost/random/geometric_distribution.hpp
dos2unix ./boost/random/inversive_congruential.hpp           ./boost/random/inversive_congruential.hpp
dos2unix ./boost/random/lagged_fibonacci.hpp                 ./boost/random/lagged_fibonacci.hpp
dos2unix ./boost/random/linear_congruential.hpp              ./boost/random/linear_congruential.hpp
dos2unix ./boost/random/lognormal_distribution.hpp           ./boost/random/lognormal_distribution.hpp
dos2unix ./boost/random/mersenne_twister.hpp                 ./boost/random/mersenne_twister.hpp
dos2unix ./boost/random/normal_distribution.hpp              ./boost/random/normal_distribution.hpp
dos2unix ./boost/random/random_number_generator.hpp          ./boost/random/random_number_generator.hpp
dos2unix ./boost/random/shuffle_output.hpp                   ./boost/random/shuffle_output.hpp
dos2unix ./boost/random/triangle_distribution.hpp            ./boost/random/triangle_distribution.hpp
dos2unix ./boost/random/uniform_01.hpp                       ./boost/random/uniform_01.hpp
dos2unix ./boost/random/uniform_int.hpp                      ./boost/random/uniform_int.hpp
dos2unix ./boost/random/uniform_on_sphere.hpp                ./boost/random/uniform_on_sphere.hpp
dos2unix ./boost/random/uniform_real.hpp                     ./boost/random/uniform_real.hpp
dos2unix ./boost/random/uniform_smallint.hpp                 ./boost/random/uniform_smallint.hpp
dos2unix ./boost/random/detail/const_mod.hpp                 ./boost/random/detail/const_mod.hpp
dos2unix ./boost/random/detail/iterator_mixin.hpp            ./boost/random/detail/iterator_mixin.hpp
dos2unix ./boost/random/detail/signed_unsigned_compare.hpp   ./boost/random/detail/signed_unsigned_compare.hpp
dos2unix ./dox/annotated.html                                ./dox/annotated.html
dos2unix ./dox/classAccess-members.html                      ./dox/classAccess-members.html
dos2unix ./dox/classAccess.html                              ./dox/classAccess.html
dos2unix ./dox/classDatabase-members.html                    ./dox/classDatabase-members.html
dos2unix ./dox/classDatabase.html                            ./dox/classDatabase.html
dos2unix ./dox/classes.html                                  ./dox/classes.html
dos2unix ./dox/classException-members.html                   ./dox/classException-members.html
dos2unix ./dox/classException.html                           ./dox/classException.html
dos2unix ./dox/classParseException-members.html              ./dox/classParseException-members.html
dos2unix ./dox/classParseException.html                      ./dox/classParseException.html
dos2unix ./dox/classSystem-members.html                      ./dox/classSystem-members.html
dos2unix ./dox/classSystem.html                              ./dox/classSystem.html
dos2unix ./dox/classTokenizer-members.html                   ./dox/classTokenizer-members.html
dos2unix ./dox/classTokenizer.html                           ./dox/classTokenizer.html
dos2unix ./dox/database_8cpp-source.html                     ./dox/database_8cpp-source.html
dos2unix ./dox/database_8cpp.html                            ./dox/database_8cpp.html
dos2unix ./dox/database_8hpp-source.html                     ./dox/database_8hpp-source.html
dos2unix ./dox/database_8hpp.html                            ./dox/database_8hpp.html
dos2unix ./dox/files.html                                    ./dox/files.html
dos2unix ./dox/functions.html                                ./dox/functions.html
dos2unix ./dox/general_8cpp-source.html                      ./dox/general_8cpp-source.html
dos2unix ./dox/general_8cpp.html                             ./dox/general_8cpp.html
dos2unix ./dox/general_8hpp-source.html                      ./dox/general_8hpp-source.html
dos2unix ./dox/general_8hpp.html                             ./dox/general_8hpp.html
dos2unix ./dox/globals.html                                  ./dox/globals.html
dos2unix ./dox/hierarchy.html                                ./dox/hierarchy.html
dos2unix ./dox/index.html                                    ./dox/index.html
dos2unix ./dox/main_8cpp-source.html                         ./dox/main_8cpp-source.html
dos2unix ./dox/main_8cpp.html                                ./dox/main_8cpp.html
dos2unix ./dox/operations_8cpp-source.html                   ./dox/operations_8cpp-source.html
dos2unix ./dox/operations_8cpp.html                          ./dox/operations_8cpp.html
dos2unix ./dox/operations_8hpp-source.html                   ./dox/operations_8hpp-source.html
dos2unix ./dox/operations_8hpp.html                          ./dox/operations_8hpp.html
dos2unix ./dox/random_8cpp-source.html                       ./dox/random_8cpp-source.html
dos2unix ./dox/random_8cpp.html                              ./dox/random_8cpp.html
dos2unix ./dox/random_8hpp-source.html                       ./dox/random_8hpp-source.html
dos2unix ./dox/random_8hpp.html                              ./dox/random_8hpp.html
dos2unix ./dox/structBlockJoin-members.html                  ./dox/structBlockJoin-members.html
dos2unix ./dox/structBlockJoin.html                          ./dox/structBlockJoin.html
dos2unix ./dox/structDeletePointer-members.html              ./dox/structDeletePointer-members.html
dos2unix ./dox/structDeletePointer.html                      ./dox/structDeletePointer.html
dos2unix ./dox/structIndex-members.html                      ./dox/structIndex-members.html
dos2unix ./dox/structIndex.html                              ./dox/structIndex.html
dos2unix ./dox/structIndexLoop-members.html                  ./dox/structIndexLoop-members.html
dos2unix ./dox/structIndexLoop.html                          ./dox/structIndexLoop.html
dos2unix ./dox/structLookup-members.html                     ./dox/structLookup-members.html
dos2unix ./dox/structLookup.html                             ./dox/structLookup.html
dos2unix ./dox/structOperation-members.html                  ./dox/structOperation-members.html
dos2unix ./dox/structOperation.html                          ./dox/structOperation.html
dos2unix ./dox/structRelation-members.html                   ./dox/structRelation-members.html
dos2unix ./dox/structRelation.html                           ./dox/structRelation.html
dos2unix ./dox/structScan-members.html                       ./dox/structScan-members.html
dos2unix ./dox/structScan.html                               ./dox/structScan.html
dos2unix ./dox/tokenizer_8hpp-source.html                    ./dox/tokenizer_8hpp-source.html
dos2unix ./dox/tokenizer_8hpp.html                           ./dox/tokenizer_8hpp.html
